# Números de vacinados da COVID-19 em todos os paises do mundo
    
## Vamos responder as perguntas: 
1. Quais são os países com maior número de pessoas imunizadas?
2. Qual vacina é a mais utilizada no mundo? ** Existem diferentes tipos de vacinas disponível no mundo
3. Qual a pais possui o maior número de vacinados por dia?
4. Qual a média de vacinação de vacinação por pais?

In [ ]:
import pandas as pd
import os

In [ ]:
path = "C:/Users/jonat/Documents/xpe/arquiteto_de_big_data/mod2/vacinados_do_virus_chines/country_vaccinations.csv"

In [41]:
df = pd.read_csv(path, sep=',', encoding='latin-1')

In [81]:

# Formate os números com separadores de milhares
df['total_vaccinations'] = df['total_vaccinations'].apply('{:,.2f}'.format)
df['people_vaccinated'] = df['people_vaccinated'].apply('{:,.2f}'.format)
df['people_fully_vaccinated'] = df['people_fully_vaccinated'].apply('{:,.2f}'.format)
df['daily_vaccinations_raw'] = df['daily_vaccinations_raw'].apply('{:,.2f}'.format)
df['daily_vaccinations'] = df['daily_vaccinations'].apply('{:,.2f}'.format)

# Defina uma função para remover zeros à direita e parte decimal se igual a zero
def remove_trailing_zeros(value):
    parts = value.split('.')
    if len(parts) == 2:
        integer_part, decimal_part = parts
        if decimal_part == '00':
            return integer_part
    return value

# Aplique a função para remover os zeros à direita e parte decimal
df['total_vaccinations'] = df['total_vaccinations'].apply(remove_trailing_zeros)
df['people_vaccinated'] = df['people_vaccinated'].apply(remove_trailing_zeros)
df['people_fully_vaccinated'] = df['people_fully_vaccinated'].apply(remove_trailing_zeros)
df['daily_vaccinations_raw'] = df['daily_vaccinations_raw'].apply(remove_trailing_zeros)
df['daily_vaccinations'] = df['daily_vaccinations'].apply(remove_trailing_zeros)

In [82]:
df.head(5)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0,0,nan,nan,nan,0.00,0.00,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,nan,nan,nan,nan,"1,367",NaN,NaN,NaN,34.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,nan,nan,nan,nan,"1,367",NaN,NaN,NaN,34.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,nan,nan,nan,nan,"1,367",NaN,NaN,NaN,34.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,nan,nan,nan,nan,"1,367",NaN,NaN,NaN,34.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

## Numero de paises distintos

In [83]:
df['country'].nunique()

223

# Dados do Brazil

In [84]:
df_brazil = df.query('country == "Brazil"').sort_values('date', ascending=False)


df_brazil

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
11085,Brazil,BRA,2022-03-29,"413,559,595","181,078,067","160,272,858","1,382,570","656,803",193.26,84.62,74.90,3069.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
11084,Brazil,BRA,2022-03-28,"412,177,025","180,881,628","160,008,924","628,823","546,999",192.61,84.53,74.77,2556.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
11083,Brazil,BRA,2022-03-27,"411,548,202","180,800,024","159,842,858","432,005","587,488",192.32,84.49,74.70,2745.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
11082,Brazil,BRA,2022-03-26,"411,116,197","180,757,995","159,756,178","255,556","548,819",192.12,84.47,74.65,2565.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
11081,Brazil,BRA,2022-03-25,"410,860,641","180,726,798","159,673,499","684,805","596,456",192.00,84.45,74.62,2787.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10653,Brazil,BRA,2021-01-21,"193,699","193,699",nan,"87,875","48,397",0.09,0.09,NaN,226.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
10652,Brazil,BRA,2021-01-20,"105,824","105,824",nan,"92,297","35,237",0.05,0.05,NaN,165.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
10651,Brazil,BRA,2021-01-19,"13,527","13,527",nan,"12,418","6,708",0.01,0.01,NaN,31.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
10650,Brazil,BRA,2021-01-18,"1,109","1,109",nan,997,997,0.00,0.00,NaN,5.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io
10649,Brazil,BRA,2021-01-17,112,112,nan,nan,nan,0.00,0.00,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",State governments via coronavirusbra1.github.io,https://coronavirusbra1.github.io

## 1. Quais são os países com maior número de pessoas imunizadas?

In [85]:
# Converter a coluna "date" para o tipo datetime para garantir que as datas sejam tratadas corretamente
df['date'] = pd.to_datetime(df['date'])

<!-- 
A função reset_index() é usada para redefinir o índice de um DataFrame do pandas. 
Ela é frequentemente usada após operações de agregação, como a função max(), que nesse caso, resulta em um índice hierárquico. 
A função reset_index() move o índice atual (neste caso, o índice hierárquico) de volta para as colunas e cria um novo índice numérico padrão.

No contexto do código, o reset_index() é usado após a operação max() para transformar o resultado em um DataFrame mais convencional. 
Sem o reset_index(), o resultado da agregação teria um índice hierárquico com os países como primeiro nível de índice e a data como segundo nível, o que pode ser menos conveniente para trabalhar em muitos casos.

Isso torna o DataFrame mais fácil de trabalhar em muitas situações, pois o índice volta a ser uma sequência numérica simples. 
-->

In [86]:
# Encontrar a última data de coleta para cada país
ultimas_datas = df.groupby('country')['date'].max().sort_values(ascending=False).reset_index()
ultimas_datas

                             country       date
0                            Lebanon 2022-03-29
1                          Lithuania 2022-03-29
2                             Kosovo 2022-03-29
3                         Kazakhstan 2022-03-29
4                              Japan 2022-03-29
..                               ...        ...
218                         Pitcairn 2021-09-07
219                     Turkmenistan 2021-09-05
220  Bonaire Sint Eustatius and Saba 2021-09-01
221                     Saint Helena 2021-05-05
222                 Falkland Islands 2021-04-14

[223 rows x 2 columns]

In [87]:

# Juntar os dados do DataFrame original com as últimas datas
dados_ultima_data = df.merge(ultimas_datas, on=['country', 'date'], how='inner')
dados_ultima_data

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2022-03-22,"5,751,015","5,082,824","4,420,127",nan,"6,319",14.44,12.76,11.10,159.00,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Albania,ALB,2022-03-24,"2,754,244","1,278,902","1,215,199",nan,"1,821",95.87,44.52,42.30,634.00,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
2,Algeria,DZA,2022-03-09,"13,704,895","7,461,932","6,110,712",nan,"4,307",30.72,16.72,13.70,97.00,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",World Health Organization,https://covid19.who.int/
3,Andorra,AND,2022-03-13,"151,997","57,817","53,367",nan,34,196.50,74.74,68.99,440.00,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",World Health Organization,https://covid19.who.int/
4,Angola,AGO,2022-03-25,"17,535,411","11,235,059","5,993,792",nan,"34,171",51.68,33.11,17.66,1007.00,Oxford/AstraZeneca,World Health Organization,https://covid19.who.int/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,Wales,OWID_WLS,2022-03-28,"6,927,437","2,528,664","2,399,341","2,254","1,609",218.53,79.77,75.69,508.00,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/vaccin...
219,Wallis and Futuna,WLF,2022-03-28,"13,073",nan,nan,nan,19,117.84,NaN,NaN,1713.00,Moderna,SPC Public Health Division,https://stats.pacificdata.org/vis?tm=covid&pg=...
220,Yemen,YEM,2022-03-16,"807,502","643,501","404,781",nan,"2,271",2.65,2.11,1.33,74.00,"Johnson&Johnson, Oxford/AstraZeneca, Sinovac",World Health Organization,https://covid19.who.int/
221,Zambia,ZMB,2022-03-29,"3,402,612",nan,"2,182,849","12,073","13,650",17.98,NaN,11.54,721.00,"Johnson&Johnson, Oxford/AstraZeneca, Sinopharm...",Government of Zambia,https://rtc-planning.maps.arcgis.com/apps/dash...
222,Zimbabwe,ZWE,2022-03-29,"9,039,729","5,053,114","3,510,256","105,369","103,751",59.90,33.48,23.26,6874.00,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

In [89]:
# pd.options.display.float_format = '{:.2f}'.format

total = df.groupby('country')['total_vaccinations'].max().sort_values(ascending=False).reset_index()
total

           country total_vaccinations
0      Afghanistan                nan
1           Russia                nan
2            Nauru                nan
3            Nepal                nan
4      Netherlands                nan
..             ...                ...
218  United States         98,253,133
219        Uruguay            975,188
220         Norway            962,762
221  Liechtenstein                952
222          Chile          9,942,308

[223 rows x 2 columns]

In [72]:
pais_brasil = total[total['country'] == 'Brazil']
print(pais_brasil)

  country  total_vaccinations
3  Brazil        413559595.00

In [60]:

imunizacoes_por_pais = dados_ultima_data[['country', 'total_vaccinations']]
imunizacoes_por_pais

               country  total_vaccinations
0          Afghanistan           5751015.0
1              Albania           2754244.0
2              Algeria          13704895.0
3              Andorra            151997.0
4               Angola          17535411.0
..                 ...                 ...
218              Wales           6927437.0
219  Wallis and Futuna             13073.0
220              Yemen            807502.0
221             Zambia           3402612.0
222           Zimbabwe           9039729.0

[223 rows x 2 columns]

In [90]:
# Ordenar os resultados em ordem decrescente com base na soma total de pessoas imunizadas
imunizacoes_por_pais_ordenadas = imunizacoes_por_pais.sort_values('total_vaccinations', ascending=False)
imunizacoes_por_pais_ordenadas.head(10)

           country  total_vaccinations
41           China       3263129000.00
91           India       1834500657.00
212  United States        560181791.00
27          Brazil        413559595.00
92       Indonesia        377108938.00
100          Japan        254345587.00
15      Bangladesh        243642749.00
151       Pakistan        219368557.00
217        Vietnam        203144374.00
127         Mexico        191907868.00

In [38]:










# Ordenar os resultados em ordem decrescente com base na soma total de pessoas imunizadas
imunizacoes_por_pais_ordenadas = imunizacoes_por_pais.sort_values(by='total_imunizadas', ascending=False)

# Selecione o país com o maior número de pessoas imunizadas
pais_com_mais_imunizadas = imunizacoes_por_pais_ordenadas.head(1)

print(pais_com_mais_imunizadas)

         people_vaccinated  people_fully_vaccinated  total_imunizadas
country
India          984838143.0              828229455.0      1.813068e+09